proxy:
    image: jwilder/nginx-proxy
    volumes:
        - /var/run/docker.sock:/tmp/docker.sock:ro
        - ./conf/ssl/certs:/etc/nginx/certs:ro
        - ./conf/proxy/default.conf:/etc/nginx/proxy.conf

# pgsql:
#     image: postgres:9.4

mysql_data:
    image: mysql:5.5

mysql:
    image: mysql:5.5
    volumes_from:
       - mysql_data

# Adminer work for mysql AND postgresql database
adminer:
    image: maxexcloo/adminer

# Send and visualize mails
maildev:
    image: djfarrelly/maildev

# Rotate logs for containers to prevent filling disk with logs
logrotate:
    image: lephare/logrotate

blackfire:
    image: blackfire/blackfire
